### PR TITLE
channel as input in read.odbc.ffdf

### PR DESCRIPTION
**Pull request by pata-eth**

### CODE REVIEW

**Comment by jwijffels** [comment]
can you make sure documentation is updated also, the read.dbi.ffdf, read.jdbc.ffdf functions have also this argument and that the connection which is passed is not closed if the channel is passed.

**Comment by pata-eth** [comment]
I was able to install the temp branch in R, but I must have messed up something. What am I missing?

**Comment by pata-eth** [comment]
it works! we can now pass the connection and avoid closing it. Is there anything else you need me to do? When do you think the current official package could be updated?

**Comment by jwijffels** [comment]
i'll have a look at this next week and upload it to CRAN

**Pull request closed without merging**
